name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CMAKE_VERSION: 3.31.3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    steps:
      - uses: actions/checkout@v4

      - name: Install cmake
        run: |
          wget -qc https://github.com/Kitware/CMake/releases/download/v${{ env.CMAKE_VERSION }}/cmake-${{ env.CMAKE_VERSION }}-linux-x86_64.tar.gz
          tar xzf cmake-${{ env.CMAKE_VERSION }}-linux-x86_64.tar.gz
          cmake-${{ env.CMAKE_VERSION }}-linux-x86_64/bin/cmake --version

      - name: Configure and build tests
        working-directory: tests
        run: |
          ${{ env.CMAKE }} -B build
          ${{ env.CMAKE }} --build build -j
        env:
          CMAKE: $GITHUB_WORKSPACE/cmake-${{ env.CMAKE_VERSION }}-linux-x86_64/bin/cmake

      - name: Run tests
        working-directory: tests
        run: ${{ env.CTEST }} --test-dir build --output-on-failure
        env:
          CTEST: $GITHUB_WORKSPACE/cmake-${{ env.CMAKE_VERSION }}-linux-x86_64/bin/ctest
