name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CMAKE_VERSION: 3.31.3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    steps:
      - uses: actions/checkout@v4

      - name: Install cmake
        run: |
          pwd
          wget -qc https://github.com/Kitware/CMake/releases/download/v${{ env.CMAKE_VERSION }}/cmake-${{ env.CMAKE_VERSION }}-linux-x86_64.tar.gz
          tar xzf cmake-${{ env.CMAKE_VERSION }}-linux-x86_64.tar.gz
          ls -phal

    #   - name: check cmake
    #     run: ${{ vars.GITHUB_WORKSPACE}}/cmake-${{ env.CMAKE_VERSION }}-linux-x86_64/bin/cmake --version

    #   - name: Configure and build
    #     working-directory: tests
    #     run: |
    #       ${{ vars.GITHUB_WORKSPACE}}/cmake-${{ env.CMAKE_VERSION }}-linux-x86_64/bin/cmake -B build
    #       cmake-${{ env.CMAKE_VERSION }}-linux-x86_64/bin/cmake --build build -j
