name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CMAKE_VERSION: v3.31.3
  CMAKE: cmake-${CMAKE_VERSION}-linux-x86_64/bin/cmake

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    steps:
      - uses: actions/checkout@v4

      - name: Install cmake
        run: |
          wget -qc https://github.com/Kitware/CMake/releases/download/${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz
          tar xzf cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz
          ${CMAKE} --version
