name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CMAKE_VERSION: 3.31.3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    steps:
      - uses: actions/checkout@v4

      - name: Install cmake
        run: wget -qc https://github.com/Kitware/CMake/releases/download/v${{ env.CMAKE_VERSION }}/cmake-${{ env.CMAKE_VERSION }}-linux-x86_64.tar.gz

      - name: Configure and build
        working-directory: tests
        run: |
          cmake-${{ env.CMAKE_VERSION }}-linux-x86_64/bin/cmake -B build
          cmake-${{ env.CMAKE_VERSION }}-linux-x86_64/bin/cmake --build build -j
